apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskserver
  labels:
    app: flaskserver
spec:
  selector:
    matchLabels:
      app: flaskserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "flaskserver"
    spec:
      containers:
        - name: flaskserver
          image: "arthurlimadossantos/flask-kubernetes:v6.7"
          
          envFrom:
            - configMapRef:
                name: flaskserver-env
            - secretRef:
                name: flaskserver-secret

          volumeMounts:
            - mountPath: "/app/myfamily"
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"